server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      # Global CORS configuration
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3001"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

      # Route definitions
      routes:
        # ========================================
        # User Service Routes
        # ========================================
        - id: user-service-auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback/user-service

        - id: user-service-users
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback/user-service

        # ========================================
        # Product Service Routes
        # ========================================
        - id: product-service-products
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackUri: forward:/fallback/product-service

        - id: product-service-brands
          uri: http://localhost:8082
          predicates:
            - Path=/api/brands/**
          filters:
            - StripPrefix=1

        - id: product-service-types
          uri: http://localhost:8082
          predicates:
            - Path=/api/types/**
          filters:
            - StripPrefix=1

        # ========================================
        # Order Service Routes
        # ========================================
        - id: order-service-orders
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackUri: forward:/fallback/order-service

        - id: order-service-cart
          uri: http://localhost:8083
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=1

        # ========================================
        # Payment Service Routes
        # ========================================
        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: payment-service
                fallbackUri: forward:/fallback/payment-service

      # Default filters applied to all routes
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY,GATEWAY_TIMEOUT
            methods: GET,POST
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
